spring:
  application:
    name: springboot
  profiles:
    active: @profiles.active@
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always

server:
  port: 8888





