dubbo:
  scan:
    base-packages: com.xiayu.consumers.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://47.93.246.173:8848
    provider:
      loadbalance: roundrobin  #负载均衡方式  轮循
      # random 随机，roundrobin 轮循，leastactive 最少活跃调用数，consistenthash一致性 Hash

management:
  endpoints:
    web:
      exposure:
        include: "*"

#oauth 配置
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://47.93.246.173:9000/oauth/token
      user-authorization-uri: http://47.93.246.173:9000/oauth/authorize
    resource:
      token-info-uri:  http://47.93.246.173:9000/oauth/check_token


# 开启 Feign 的 OKHttp 方式
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false