spring:
  application:
    name: springboot
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always


mybatis:
  type-aliases-package: com.xiayu.springboot_demo.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 9999